# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: QA-Test-$(date:yyyyMMdd)$(rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: e2e-automation/
  mavenRepoName: KornFerry.IntelligenceCloud.QAAutomation.Library

steps:
  - checkout: self

  - task: MavenAuthenticate@0
    displayName: "Maven Authenticate"
    inputs:
      artifactsFeeds: "$(mavenRepoName)"

  - task: Maven@3
    displayName: "Run E2E Tests"
    inputs:
      mavenPomFile: "$(workingDirectory)/pom.xml"
      goals: "clean install"
      publishJUnitResults: true
      testResultsFiles: "**/TEST-*.xml"
      javaHomeOption: "JDKVersion"
      mavenVersionOption: "Default"
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
    env:
      AZURE_TENANT_ID: $(azureTenantId)
      AZURE_CLIENT_ID: $(azureClientId)
      AZURE_CLIENT_SECRET: $(azureClientSecret)
